### ISSUE TITLE
Python 不支持同名函数，所以openapi里第二个sendMessage会覆盖第一个。

### ISSUE THREAD

**Issue by MarisaDAZA** [yhchat/bot-python-sdk#2]
Python 不支持同名函数，所以openapi里第二个sendMessage会覆盖第一个。

**Comment by MarisaDAZA** [comment]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Openapi.sendMessage() missing 4 required positional arguments: 'recvId', 'recvType', 'contentType', and 'content'

**Comment by jhhnjhhn** [comment]
已修复，第一个“sendMessage”方法改成“sendTextMessage”
https://github.com/yhchat/bot-python-sdk/commit/8e997a50abdc7f091d7a0b0dd6dc4152100c164d
